// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmnAJT5GyIu74Un3CBood7VsZjmbkHJz0',
    appId: '1:1037679837787:android:7b61a8f07259313728357e',
    messagingSenderId: '1037679837787',
    projectId: 'medicircl',
    storageBucket: 'medicircl.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTOs3CffmHtTrFgqPOg4zUd1yOmr9yCf4',
    appId: '1:1037679837787:web:423e2ecba4defed728357e',
    messagingSenderId: '1037679837787',
    projectId: 'medicircl',
    authDomain: 'medicircl.firebaseapp.com',
    storageBucket: 'medicircl.firebasestorage.app',
    measurementId: 'G-HTJRX59LFV',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTOs3CffmHtTrFgqPOg4zUd1yOmr9yCf4',
    appId: '1:1037679837787:web:e6705e6a856b798e28357e',
    messagingSenderId: '1037679837787',
    projectId: 'medicircl',
    authDomain: 'medicircl.firebaseapp.com',
    storageBucket: 'medicircl.firebasestorage.app',
    measurementId: 'G-JNG6ZED44V',
  );

}